[package]
name = "flshift"
version = "0.1.0"
authors = ["Markus Røyset <cosmicspacedragon@gmail.com>"]
edition = "2018"

[[bin]]
name = "flshift"

[lib]
name = "flshift"

[dependencies]
structopt = "0.2.15"
